import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Mi Página</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" />
      </head>
      <body className="body-style">
        <header className="header-style">
          <nav>
            <ul className="nav-list">
              <li><a href="/">Inicio</a></li>
              <li><a href="/login">Login</a></li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="footer-style">
          <p>&copy; 2025 Mi Página. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
